# docker-compose for Pontoon development.
#
# Note: Requires docker-compose 1.10+.
version: '2.3'
services:
  server:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: server
    image: local/pontoon
    env_file:
      - docker/config/server.env
    depends_on:
      - postgresql
    ports:
      - '8000:8000'
    volumes:
      - ./pontoon:/app/pontoon
      - ./requirements:/app/requirements
      - ./tag-admin:/app/tag-admin
      - ./translate:/app/translate
      - ~/.ssh:/home/pontoon/.ssh

    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.server.rule=Host(`pontoon.flowertop.xyz`)'
      - 'traefik.http.routers.server.entrypoints=websecure'
      - 'traefik.http.routers.server.tls.certresolver=myresolver'
      - 'traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https'
      - 'traefik.http.routers.redirs.rule=hostregexp(`{host:.+}`)'
      - 'traefik.http.routers.redirs.entrypoints=web'
      - 'traefik.http.routers.redirs.middlewares=redirect-to-https'

  reverse-proxy:
    image: traefik:v2.4
    container_name: 'traefik'
    command:
      - '--api.insecure=true'
      - '--api.dashboard=true'
      - '--api.debug=true'
      - '--providers.docker=true'
      - '--log.LEVEL=DEBUG'
      - '--entryPoints.web.address=:80'
      - '--entryPoints.websecure.address=:443'
      - '--providers.docker.exposedbydefault=false'
      - '--certificatesresolvers.myresolver.acme.httpchallenge=true'
      - '--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web'
      - '--certificatesresolvers.myresolver.acme.email=eddy@bitnob.com'
      - '--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json'
    ports:
      - '443:443'
      - '80:80'
      - '8080:8080'
    volumes:
      - './letsencrypt:/letsencrypt'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'

  # Database
  postgresql:
    image: postgres:15
    environment:
      # Create the superuser account
      - POSTGRES_USER=pontoon
      - POSTGRES_PASSWORD=asdf
      - POSTGRES_DB=pontoon
    volumes:
      - pgdata:/var/lib/postgresql/data

# Persist database
volumes:
  pgdata: null
